export const GET_STATISTIC = 'GET_STATISTIC';
export const GET_DIAGRAM_STATISTIC = 'GET_DIAGRAM_STATISTIC';
export const GET_MAP_STATISTIC = 'GET_MAP_STATISTIC';
export const GET_RADAR_DIAGRAM_STATISTIC = 'GET_RADAR_DIAGRAM_STATISTIC';
export const GET_REGION_TOP_STATISTIC = 'GET_REGION_TOP_STATISTIC';
